# Copie este arquivo para secrets.toml na raiz do projeto OU para .streamlit/secrets.toml.
# Preencha com os dados do JSON baixado em Google Cloud > Service Accounts > Keys.

[google_calendar]
calendar_id = "caioanalistadados@gmail.com"

[google_service_account]
type = "service_account"
project_id = "SEU_PROJECT_ID"
private_key_id = "SEU_PRIVATE_KEY_ID"
private_key = """-----BEGIN PRIVATE KEY-----
SUA_CHAVE_PRIVADA
-----END PRIVATE KEY-----
"""
client_email = "SUA_SERVICE_ACCOUNT@SEU_PROJETO.iam.gserviceaccount.com"
client_id = "SEU_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "SUA_URL_X509"
universe_domain = "googleapis.com"
